services:
  fastapi_app:
    build:
      context: api
      dockerfile: Dockerfile
    image: mlops_monitoring_demo_api:latest
    container_name: fastapi
    restart: always
    volumes:
      - ./:/home/api
    ports:
      - 5010:5010
    networks:
      - monitoring

  streamlit_app:
    build:
      context: dashboard
      dockerfile: Dockerfile
    image: mlops_monitoring_demo_dashboard:latest
    container_name: streamlit
    restart: always
    volumes:
      - ./dashboard:/home/dashboard
    environment:
      - FASTAPI_APP_HOST=fastapi_app
    ports:
      - 8501:8501
    networks:
      - monitoring

volumes:
  monitoring_db_data: {}

networks:
  monitoring:
    name: monitoring
