services:
  fastapi_app:
    build:
      context: api
      dockerfile: Dockerfile
    image: from-jupyter-to-production-monitoring-api:latest
    restart: always
    ports:
      - 5010:5010
    networks:
      - monitoring

  streamlit_app:
    build:
      context: dashboard
      dockerfile: Dockerfile
    image: from-jupyter-to-production-monitoring-dashboard:latest
    restart: always
    environment:
      - FASTAPI_APP_HOST=fastapi_app
    ports:
      - 8501:8501
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
